version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      k8s.io:
        patterns:
          - "k8s.io/api"
          - "k8s.io/apimachinery"
          - "k8s.io/cli-runtime"
          - "k8s.io/client-go"
          - "k8s.io/kubectl"
          - "k8s.io/metrics"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
