apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aks-periscope

bases:
- ../../base

images:
- name: periscope-linux
  newName: mcr.microsoft.com/aks/periscope
  newTag: "${IMAGE_TAG}"
- name: periscope-windows
  newName: mcr.microsoft.com/aks/periscope-win
  newTag: "${IMAGE_TAG}"

secretGenerator:
- name: azureblob-secret
  behavior: replace
  literals:
  - AZURE_BLOB_SAS_KEY=${SAS_KEY_PLACEHOLDER}

# Consuming applications perform substitutions for account/container in unencoded text.
# For compatibility, use a ConfigMap.
configMapGenerator:
- name: storage-config
  literals:
  - AZURE_BLOB_ACCOUNT_NAME=${ACCOUNT_NAME_PLACEHOLDER}
  - AZURE_BLOB_CONTAINER_NAME=${CONTAINER_NAME_PLACEHOLDER}

patches:
- target:
    group: apps
    kind: DaemonSet
    name: aks-periscope
    version: v1
  patch: |-
    - op: add
      path: '/spec/template/spec/containers/0/envFrom/-'
      value:
        configMapRef:
          name: storage-config
- target:
    group: apps
    kind: DaemonSet
    name: aks-periscope-win
    version: v1
  patch: |-
    - op: add
      path: '/spec/template/spec/containers/0/envFrom/-'
      value:
        configMapRef:
          name: storage-config

generatorOptions:
  disableNameSuffixHash: true