# Builder
FROM golang:1.19.5-alpine AS builder
RUN apk add git

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /build

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -buildvcs=false ./cmd/aks-periscope

# Runner
FROM alpine

COPY --from=builder /build/aks-periscope /

ENTRYPOINT ["/aks-periscope"]
