# Builder
FROM golang:1.19.5-windowsservercore-1809 AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=windows \
    GOARCH=amd64

WORKDIR /build

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -buildvcs=false ./cmd/aks-periscope

# Runner
FROM mcr.microsoft.com/windows/servercore:1809

COPY --from=builder /build/aks-periscope.exe /

ENTRYPOINT ["/aks-periscope.exe"]
