name: Building and Pushing to MCR
on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read

jobs: 
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-2019]
        include:
        - os: ubuntu-latest
          file: ./builder/Dockerfile.linux
          imagename: 'aks/periscope'
        - os: windows-2019
          file: ./builder/Dockerfile.windows
          imagename: 'aks/periscope-win'
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v2
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          path: ./CHANGELOG.md
      - name: Display output
        run: |
           echo "Version: ${{ steps.changelog_reader.outputs.version }}"
           echo "Changes: ${{ steps.changelog_reader.outputs.changes }}"
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure CLI commands'
        run: |
          docker build -f ${{ matrix.file }} -t ${{ secrets.AZURE_REGISTRY_SERVER }}/public/${{ matrix.imagename }}:${{ steps.changelog_reader.outputs.version }} .
          az acr login -n ${{ secrets.AZURE_REGISTRY_SERVER }}
          docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/public/${{ matrix.imagename }}:${{ steps.changelog_reader.outputs.version }}
          echo "acr push done"